### ISSUE TITLE
AWS Response 

### ISSUE THREAD

**Issue by bruceharrison1984** [XT-i/aws-lambda-jenkins-plugin#39]
Using an AWS Lambda build action with any JSON Parameters for parsing or capturing the response causes the following failure.

`ERROR: Build step failed with exception
java.lang.RuntimeException: java.io.IOException: Unable to serialize com.xti.jenkins.plugin.awslambda.callable.InvokeCallable@3357275a
	at com.xti.jenkins.plugin.awslambda.invoke.LambdaInvokePublisher.perform(LambdaInvokePublisher.java:112)
	at com.xti.jenkins.plugin.awslambda.invoke.LambdaInvokePublisher.perform(LambdaInvokePublisher.java:75)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: Unable to serialize com.xti.jenkins.plugin.awslambda.callable.InvokeCallable@3357275a
	at hudson.remoting.UserRequest.serialize(UserRequest.java:168)
	at hudson.remoting.UserRequest.<init>(UserRequest.java:62)
	at hudson.remoting.Channel.call(Channel.java:779)
	at com.xti.jenkins.plugin.awslambda.invoke.LambdaInvokePublisher.perform(LambdaInvokePublisher.java:99)
	... 10 more
Caused by: java.io.NotSerializableException: com.xti.jenkins.plugin.awslambda.invoke.JsonParameter
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at java.util.ArrayList.writeObject(ArrayList.java:742)
	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1495)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:157)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:166)
	... 13 more
Build step 'AWS Lambda invocation' marked build as failure
Finished: FAILURE`

This occurs when the step is a build step, as well as a post-build action. Removing the JSON Paramenters allows the step to complete successfully. This also happens with or without a JSON payload being sent with the original request.

Had the same issue with version 0.4.3 as well as 0.5.0

**Comment by cast** [comment]
Accepted, fix on the way for next release 0.5.1

**Comment by bruceharrison1984** [comment]
Fixed and working in our production environment. Thanks!
