### ISSUE TITLE
Support for Region eu-west-2 (London)

### ISSUE THREAD

**Issue by pgrabarczyk** [XT-i/aws-lambda-jenkins-plugin#90]
It's look like plugin use old version of AWS SDK that not support London region.

`Started by timer
Building in workspace /var/lib/jenkins/workspace/lambda_create_ami
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Cannot create enum from eu-west-2 value!
	at com.amazonaws.regions.Regions.fromName(Regions.java:76)
	at com.xti.jenkins.plugin.awslambda.util.LambdaClientConfig.getClient(LambdaClientConfig.java:35)
	at com.xti.jenkins.plugin.awslambda.callable.InvokeCallable.call(InvokeCallable.java:41)
	at com.xti.jenkins.plugin.awslambda.callable.InvokeCallable.call(InvokeCallable.java:25)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at com.xti.jenkins.plugin.awslambda.invoke.LambdaInvokeBuildStep.perform(LambdaInvokeBuildStep.java:77)
Caused: java.lang.RuntimeException
	at com.xti.jenkins.plugin.awslambda.invoke.LambdaInvokeBuildStep.perform(LambdaInvokeBuildStep.java:87)
	at com.xti.jenkins.plugin.awslambda.invoke.LambdaInvokeBuildStep.perform(LambdaInvokeBuildStep.java:65)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'AWS Lambda invocation' marked build as failure
Finished: FAILURE`

Plugin version: 0.5.10

**Comment by pgrabarczyk** [comment]
I just found that someone tried to fix it already

[](https://github.com/XT-i/aws-lambda-jenkins-plugin/pull/81)
